branchName: '#${issue.number}-${issue.title}'
branches:
  - label: feature
    prefix: feature/
  - label: bug
    prefix: bugfix/
  - label: design
    prefix: design/
  - label: refactoring
    prefix: refactoring/
autoCloseIssue: true
